In [6]:
# import libraries
import pandas as pd

In [7]:
# load in flat file as df
df = pd.read_csv('../Data/bookstore_flat.csv')

In [8]:
# inspect the df
df.head()

,transaction_id,transaction_date,member_id,member_first_name,member_last_name,member_email,member_tier,member_join_date,member_city,member_state,...,author_first,author_last,publisher_name,publisher_city,publisher_country,publication_year,list_price,quantity,discount_percent,sale_total
0,1,2019-10-05,260,Casey,Jackson,casey.jackson260@email.com,Platinum,2018-12-09,New York,WA,...,Celeste,Ng,Macmillan Publishers,New York,USA,2006,19.23,3,20,46.14
1,2,2019-12-22,292,Marcus,Walker,marcus.walker292@email.com,Platinum,2020-06-11,Portland,CO,...,Erik,Larson,Hachette Book Group,New York,USA,2008,28.46,1,0,28.46
2,3,2019-03-09,30,Bailey,Anderson,bailey.anderson30@email.com,Bronze,2018-05-26,Austin,TX,...,Isabel,Allende,Scholastic,New York,USA,2020,34.94,1,5,33.19
3,4,2020-02-12,185,Ethan,King,ethan.king185@email.com,Bronze,2018-01-05,Portland,CA,...,Jhumpa,Lahiri,Penguin Random House,New York,USA,2012,31.17,2,0,62.34
4,5,2021-03-23,238,Kenji,Scott,kenji.scott238@email.com,Gold,2022-10-28,Coral Gables,OR,...,N.K.,Jemisin,Hachette Book Group,New York,USA,2007,19.10,1,15,16.23

Use this markdown cell to write notes needed to design the new relational db schema

In [ ]:
df.columns

Index(['transaction_id', 'transaction_date', 'member_id', 'member_first_name',
       'member_last_name', 'member_email', 'member_tier', 'member_join_date',
       'member_city', 'member_state', 'store_name', 'store_city',
       'store_state', 'store_region', 'book_id', 'isbn', 'title', 'genre',
       'format', 'author_first', 'author_last', 'publisher_name',
       'publisher_city', 'publisher_country', 'publication_year', 'list_price',
       'quantity', 'discount_percent', 'sale_total'],
      dtype='str')

Use this markdoen cell to write notes needed tp design tje new relational database

Tables:
- tranactions - ['transaction_id', 'transcation_date', member_id', book_id', 'store_id', 'quantity', 'discount_percent'] ***store_id
- members - ['member_id', 'member_first_name', 'member_last_name', 'member_email', 'member_tier', 'member_join_date', 'member_city', 'member_state']
- stores - ['store_name', ' store_city', 'store_state', 'store_region'] ***store_id
- books - ['book_id', 'isbn', 'title', 'genre', 'format', 'author_id', 'publisher_id', 'list_price', 'publication_year'] *** genre_id, author_id, publisher_id
- publishers - ['publisher_name, 'publisher_city', 'publisher_country'] *** publisher_id
- genres - ?? we have to look up unique ->['genre_id', 'name']
- authors - ['author_id', 'author_first', 'author_last'] *** author_id

In [13]:
# filter the df into tables matching the schema above
genres_df = df[['genre']].drop_duplicates().reset_index(drop=True)

In [16]:
genres_df.head()

   genre_id            genre
0         1        Biography
1         2          History
2         3  Science Fiction
3         4          Fiction
4         5          Mystery

In [15]:
genres_df.insert(0, 'genre_id', range(1, len(genres_df) + 1))

In [17]:
genres_df = genres_df.rename(columns={'genre':'name'})
genres_df

   genre_id             name
0         1        Biography
1         2          History
2         3  Science Fiction
3         4          Fiction
4         5          Mystery
5         6          Fantasy
6         7        Self-Help

In [48]:
authors_df = df[['author_first', 'author_last']].drop_duplicates().reset_index(drop=True)
authors_df.head(20)

   author_first author_last
0       Celeste          Ng
1          Erik      Larson
2        Isabel     Allende
3        Jhumpa      Lahiri
4          N.K.     Jemisin
5       Patrick    Rothfuss
6         Ocean       Vuong
7        Colson   Whitehead
8         Zadie       Smith
9        Roxane         Gay
10      Malcolm    Gladwell
11      Anthony       Doerr
12    Ta-Nehisi      Coates
13      Stephen        King
14        Sally      Rooney
15      Min Jin         Lee
16     Michelle       Obama
17        Kazuo    Ishiguro
18        James   Patterson
19        Donna       Tartt

In [49]:
authors_df.insert(0, 'author_id', range(1, len(authors_df) + 1))
authors_df.head(20)

    author_id author_first author_last
0           1      Celeste          Ng
1           2         Erik      Larson
2           3       Isabel     Allende
3           4       Jhumpa      Lahiri
4           5         N.K.     Jemisin
5           6      Patrick    Rothfuss
6           7        Ocean       Vuong
7           8       Colson   Whitehead
8           9        Zadie       Smith
9          10       Roxane         Gay
10         11      Malcolm    Gladwell
11         12      Anthony       Doerr
12         13    Ta-Nehisi      Coates
13         14      Stephen        King
14         15        Sally      Rooney
15         16      Min Jin         Lee
16         17     Michelle       Obama
17         18        Kazuo    Ishiguro
18         19        James   Patterson
19         20        Donna       Tartt

In [50]:
authors_df = authors_df.rename(columns={'authors_id': 'author_id', 'author_first': 'first_name', 'author_last': 'last_name'})
authors_df.head(10)

   author_id first_name  last_name
0          1    Celeste         Ng
1          2       Erik     Larson
2          3     Isabel    Allende
3          4     Jhumpa     Lahiri
4          5       N.K.    Jemisin
5          6    Patrick   Rothfuss
6          7      Ocean      Vuong
7          8     Colson  Whitehead
8          9      Zadie      Smith
9         10     Roxane        Gay

In [21]:
publishers_df = df[['publisher_name', 'publisher_city', 'publisher_country']].drop_duplicates().reset_index(drop=True)
publishers_df.insert(0, 'publisher_id', range(1, len(publishers_df) + 1))
publishers_df.head(10)

   publisher_id        publisher_name publisher_city publisher_country
0             1  Macmillan Publishers       New York               USA
1             2   Hachette Book Group       New York               USA
2             3            Scholastic       New York               USA
3             4  Penguin Random House       New York               USA
4             5            Bloomsbury         London                UK
5             6      Simon & Schuster       New York               USA
6             7                 Knopf       New York               USA
7             8         HarperCollins       New York               USA
8             9  Farrar Straus Giroux       New York               USA
9            10         Vintage Books       New York               USA

In [22]:
stores_df = df[['store_name', 'store_city', 'store_state', 'store_region']].drop_duplicates().reset_index(drop=True)
stores_df.insert(0, 'store_id', range(1, len(stores_df) + 1))
stores_df.head(10)

   store_id            store_name     store_city store_state store_region
0         1        Prairie Lights      Iowa City          IA      Midwest
1         2        Powell's Books       Portland          OR      Pacific
2         3            BookPeople         Austin          TX        South
3         4       Left Bank Books      St. Louis          MO      Midwest
4         5  Malaprop's Bookstore      Asheville          NC        South
5         6    Elliot Bay Book Co        Seattle          WA      Pacific
6         7    Harvard Book Store      Cambridge          MA    Northeast
7         8         Books & Books   Coral Gables          FL        South
8         9         The Booksmith  San Francisco          CA      Pacific
9        10        Tattered Cover         Denver          CO     Mountain

In [23]:
members_df = df[['member_id', 'member_first_name', 'member_last_name', 'member_email', 'member_tier', 'member_join_date','member_city', 'member_state']].drop_duplicates().reset_index(drop=True)
members_df.head(10)

,member_id,member_first_name,member_last_name,member_email,member_tier,member_join_date,member_city,member_state
0,260,Casey,Jackson,casey.jackson260@email.com,Platinum,2018-12-09,New York,WA
1,292,Marcus,Walker,marcus.walker292@email.com,Platinum,2020-06-11,Portland,CO
2,30,Bailey,Anderson,bailey.anderson30@email.com,Bronze,2018-05-26,Austin,TX
3,185,Ethan,King,ethan.king185@email.com,Bronze,2018-01-05,Portland,CA
4,238,Kenji,Scott,kenji.scott238@email.com,Gold,2022-10-28,Coral Gables,OR
5,16,Hector,Green,hector.green16@email.com,Gold,2023-03-16,Coral Gables,FL
6,91,Ethan,Walker,ethan.walker91@email.com,Silver,2018-05-25,Cambridge,CA
7,84,Kenji,White,kenji.white84@email.com,Silver,2022-04-20,Cambridge,CA
8,146,Alex,Davis,alex.davis146@email.com,Gold,2020-07-19,Menlo Park,MA
9,293,Iris,Jackson,iris.jackson293@email.com,Platinum,2016-08-12,Portland,IA

In [24]:
books_df = df[['book_id', 'isbn', 'title', 'genre', 'format', 'author_first', 'author_last', 'publisher_name', 'list_price', 'publication_year']].drop_duplicates().reset_index(drop=True)
books_df.head(10)

,book_id,isbn,title,genre,format,author_first,author_last,publisher_name,list_price,publication_year
0,182,978-529-93748-89-7,The Long Road Vol. 6,Biography,Paperback,Celeste,Ng,Macmillan Publishers,19.23,2006
1,226,978-119-67807-50-6,The Lost Century Vol. 2,History,Hardcover,Erik,Larson,Hachette Book Group,28.46,2008
2,215,978-578-75373-49-7,Empire Rising Vol. 7,History,Paperback,Isabel,Allende,Scholastic,34.94,2020
3,236,978-856-14888-32-6,Turning Points Vol. 4,History,Hardcover,Jhumpa,Lahiri,Penguin Random House,31.17,2012
4,211,978-161-30719-66-6,Empire Rising Vol. 3,History,Audiobook,N.K.,Jemisin,Hachette Book Group,19.10,2007
5,175,978-936-36174-87-2,Against All Odds Vol. 7,Biography,Audiobook,Patrick,Rothfuss,Macmillan Publishers,26.09,2018
6,115,978-923-70981-46-8,First Contact Vol. 3,Science Fiction,Audiobook,Ocean,Vuong,Macmillan Publishers,17.67,2005
7,89,978-518-69048-98-9,The Outer Reaches,Science Fiction,Paperback,Colson,Whitehead,Hachette Book Group,27.76,2010
8,24,978-789-95649-92-1,A Thousand Tomorrows Vol. 8,Fiction,eBook,Zadie,Smith,Bloomsbury,23.39,2019
9,219,978-386-91689-97-9,When Nations Fall Vol. 3,History,Hardcover,Roxane,Gay,Macmillan Publishers,22.13,2019

In [26]:
books_df = books_df.merge(genres_df[['genre_id', 'name']], left_on='genre', right_on='name', how='left')
books_df.head(10)

,book_id,isbn,title,genre,format,author_first,author_last,publisher_name,list_price,publication_year,genre_id,name
0,182,978-529-93748-89-7,The Long Road Vol. 6,Biography,Paperback,Celeste,Ng,Macmillan Publishers,19.23,2006,1,Biography
1,226,978-119-67807-50-6,The Lost Century Vol. 2,History,Hardcover,Erik,Larson,Hachette Book Group,28.46,2008,2,History
2,215,978-578-75373-49-7,Empire Rising Vol. 7,History,Paperback,Isabel,Allende,Scholastic,34.94,2020,2,History
3,236,978-856-14888-32-6,Turning Points Vol. 4,History,Hardcover,Jhumpa,Lahiri,Penguin Random House,31.17,2012,2,History
4,211,978-161-30719-66-6,Empire Rising Vol. 3,History,Audiobook,N.K.,Jemisin,Hachette Book Group,19.10,2007,2,History
5,175,978-936-36174-87-2,Against All Odds Vol. 7,Biography,Audiobook,Patrick,Rothfuss,Macmillan Publishers,26.09,2018,1,Biography
6,115,978-923-70981-46-8,First Contact Vol. 3,Science Fiction,Audiobook,Ocean,Vuong,Macmillan Publishers,17.67,2005,3,Science Fiction
7,89,978-518-69048-98-9,The Outer Reaches,Science Fiction,Paperback,Colson,Whitehead,Hachette Book Group,27.76,2010,3,Science Fiction
8,24,978-789-95649-92-1,A Thousand Tomorrows Vol. 8,Fiction,eBook,Zadie,Smith,Bloomsbury,23.39,2019,4,Fiction
9,219,978-386-91689-97-9,When Nations Fall Vol. 3,History,Hardcover,Roxane,Gay,Macmillan Publishers,22.13,2019,2,History

In [27]:
books_df = books_df.drop(columns=['genre', 'name'])
books_df.head(10)

,book_id,isbn,title,format,author_first,author_last,publisher_name,list_price,publication_year,genre_id
0,182,978-529-93748-89-7,The Long Road Vol. 6,Paperback,Celeste,Ng,Macmillan Publishers,19.23,2006,1
1,226,978-119-67807-50-6,The Lost Century Vol. 2,Hardcover,Erik,Larson,Hachette Book Group,28.46,2008,2
2,215,978-578-75373-49-7,Empire Rising Vol. 7,Paperback,Isabel,Allende,Scholastic,34.94,2020,2
3,236,978-856-14888-32-6,Turning Points Vol. 4,Hardcover,Jhumpa,Lahiri,Penguin Random House,31.17,2012,2
4,211,978-161-30719-66-6,Empire Rising Vol. 3,Audiobook,N.K.,Jemisin,Hachette Book Group,19.10,2007,2
5,175,978-936-36174-87-2,Against All Odds Vol. 7,Audiobook,Patrick,Rothfuss,Macmillan Publishers,26.09,2018,1
6,115,978-923-70981-46-8,First Contact Vol. 3,Audiobook,Ocean,Vuong,Macmillan Publishers,17.67,2005,3
7,89,978-518-69048-98-9,The Outer Reaches,Paperback,Colson,Whitehead,Hachette Book Group,27.76,2010,3
8,24,978-789-95649-92-1,A Thousand Tomorrows Vol. 8,eBook,Zadie,Smith,Bloomsbury,23.39,2019,4
9,219,978-386-91689-97-9,When Nations Fall Vol. 3,Hardcover,Roxane,Gay,Macmillan Publishers,22.13,2019,2

In [28]:
books_df = books_df.merge(authors_df[['author_id', 'first_name', 'last_name']], left_on=['author_first', 'author_last'], right_on=['first_name', 'last_name'], how='left')
books_df.head(10)

,book_id,isbn,title,format,author_first,author_last,publisher_name,list_price,publication_year,genre_id,author_id,first_name,last_name
0,182,978-529-93748-89-7,The Long Road Vol. 6,Paperback,Celeste,Ng,Macmillan Publishers,19.23,2006,1,1,Celeste,Ng
1,226,978-119-67807-50-6,The Lost Century Vol. 2,Hardcover,Erik,Larson,Hachette Book Group,28.46,2008,2,2,Erik,Larson
2,215,978-578-75373-49-7,Empire Rising Vol. 7,Paperback,Isabel,Allende,Scholastic,34.94,2020,2,3,Isabel,Allende
3,236,978-856-14888-32-6,Turning Points Vol. 4,Hardcover,Jhumpa,Lahiri,Penguin Random House,31.17,2012,2,4,Jhumpa,Lahiri
4,211,978-161-30719-66-6,Empire Rising Vol. 3,Audiobook,N.K.,Jemisin,Hachette Book Group,19.10,2007,2,5,N.K.,Jemisin
5,175,978-936-36174-87-2,Against All Odds Vol. 7,Audiobook,Patrick,Rothfuss,Macmillan Publishers,26.09,2018,1,6,Patrick,Rothfuss
6,115,978-923-70981-46-8,First Contact Vol. 3,Audiobook,Ocean,Vuong,Macmillan Publishers,17.67,2005,3,7,Ocean,Vuong
7,89,978-518-69048-98-9,The Outer Reaches,Paperback,Colson,Whitehead,Hachette Book Group,27.76,2010,3,8,Colson,Whitehead
8,24,978-789-95649-92-1,A Thousand Tomorrows Vol. 8,eBook,Zadie,Smith,Bloomsbury,23.39,2019,4,9,Zadie,Smith
9,219,978-386-91689-97-9,When Nations Fall Vol. 3,Hardcover,Roxane,Gay,Macmillan Publishers,22.13,2019,2,10,Roxane,Gay

In [30]:
books_df = books_df.drop(columns=['first_name', 'last_name'])
books_df.head(10)

,book_id,isbn,title,format,author_first,author_last,publisher_name,list_price,publication_year,genre_id,author_id
0,182,978-529-93748-89-7,The Long Road Vol. 6,Paperback,Celeste,Ng,Macmillan Publishers,19.23,2006,1,1
1,226,978-119-67807-50-6,The Lost Century Vol. 2,Hardcover,Erik,Larson,Hachette Book Group,28.46,2008,2,2
2,215,978-578-75373-49-7,Empire Rising Vol. 7,Paperback,Isabel,Allende,Scholastic,34.94,2020,2,3
3,236,978-856-14888-32-6,Turning Points Vol. 4,Hardcover,Jhumpa,Lahiri,Penguin Random House,31.17,2012,2,4
4,211,978-161-30719-66-6,Empire Rising Vol. 3,Audiobook,N.K.,Jemisin,Hachette Book Group,19.10,2007,2,5
5,175,978-936-36174-87-2,Against All Odds Vol. 7,Audiobook,Patrick,Rothfuss,Macmillan Publishers,26.09,2018,1,6
6,115,978-923-70981-46-8,First Contact Vol. 3,Audiobook,Ocean,Vuong,Macmillan Publishers,17.67,2005,3,7
7,89,978-518-69048-98-9,The Outer Reaches,Paperback,Colson,Whitehead,Hachette Book Group,27.76,2010,3,8
8,24,978-789-95649-92-1,A Thousand Tomorrows Vol. 8,eBook,Zadie,Smith,Bloomsbury,23.39,2019,4,9
9,219,978-386-91689-97-9,When Nations Fall Vol. 3,Hardcover,Roxane,Gay,Macmillan Publishers,22.13,2019,2,10

In [33]:
trans_df = df[['transaction_id', 'transaction_date', 'member_id', 'book_id', 'store_name', 'quantity', 'discount_percent']].drop_duplicates()
trans_df.head(10)

,transaction_id,transaction_date,member_id,book_id,store_name,quantity,discount_percent
0,1,2019-10-05,260,182,Prairie Lights,3,20
1,2,2019-12-22,292,226,Powell's Books,1,0
2,3,2019-03-09,30,215,BookPeople,1,5
3,4,2020-02-12,185,236,Left Bank Books,2,0
4,5,2021-03-23,238,211,Malaprop's Bookstore,1,15
5,6,2021-02-01,16,175,BookPeople,3,5
6,7,2022-04-16,91,115,Elliot Bay Book Co,2,10
7,8,2023-03-14,84,89,Harvard Book Store,3,20
8,9,2021-03-02,146,24,Powell's Books,1,0
9,10,2023-10-22,293,219,BookPeople,3,0

In [53]:
trans_df = trans_df.merge(stores_df[['store_id']], left_on=['store_id'], right_on=['store_id'], how='left')
trans_df.head(10)

KeyError: 'store_id'

In [ ]:
# save each of the new dfs as their own csv files

In [ ]:
# create the database and load all new dfs as tables. make sure to save the db in the data folder.